baseurl = "https://yenskr.netlify.com/"
title = "Yenskrrr"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
enableEmoji = true
# pygmentsCodefences = true
# disqusShortname = "yenskr"
# pygmentsStyle = "Zenburn"
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[taxonomies]
  series = "series"

[params]
    author = "Yenskrrr"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = """
        Yenping's blog about R, Shiny, Leaflet, data visualization and other cool stuff. SKRRR!
    """
    publicationYear = "2019"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

[outputs]
    section = ["JSON", "HTML"]
    
[[menu.main]]
    identifier = "about"
    name = "About" #If display text link, cancel comment out
    pre = "<i class='fas fa-user fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/about/about-me/"
    weight = 5    

[[menu.main]]
    identifier = "blog"
    name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/blog/"
    weight = 10

[[menu.main]]
    identifier = "twitter"
    name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/username"
    weight = 20

[[menu.main]]
    identifier = "github"
    name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/username"
    weight = 30

[[menu.main]]
    identifier = "email"
    name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:username@example.com"
    weight = 40
